error: App running on port:4000
[31merror[39m: syntax error at or near "return" {"code":"42601","file":"scan.l","length":95,"line":"1176","name":"error","position":"41","routine":"scanner_yyerror","service":"Practice_App","severity":"ERROR"}
[31merror[39m: syntax error at or near "return" {"code":"42601","file":"scan.l","length":95,"line":"1176","name":"error","position":"41","routine":"scanner_yyerror","service":"Practice_App","severity":"ERROR"}
[31merror[39m: getaddrinfo EAI_AGAIN db {"code":"EAI_AGAIN","errno":-3001,"hostname":"db","service":"Practice_App","syscall":"getaddrinfo"}
[31merror[39m: getaddrinfo EAI_AGAIN db {"code":"EAI_AGAIN","errno":-3001,"hostname":"db","service":"Practice_App","syscall":"getaddrinfo"}
[31merror[39m: getaddrinfo EAI_AGAIN db {"code":"EAI_AGAIN","errno":-3001,"hostname":"db","service":"Practice_App","syscall":"getaddrinfo"}
[31merror[39m: getaddrinfo EAI_AGAIN db {"code":"EAI_AGAIN","errno":-3001,"hostname":"db","service":"Practice_App","syscall":"getaddrinfo"}
[31merror[39m: getaddrinfo EAI_AGAIN db {"code":"EAI_AGAIN","errno":-3001,"hostname":"db","service":"Practice_App","syscall":"getaddrinfo"}
[31merror[39m: getaddrinfo EAI_AGAIN db {"code":"EAI_AGAIN","errno":-3001,"hostname":"db","service":"Practice_App","syscall":"getaddrinfo"}
[31merror[39m: getaddrinfo EAI_AGAIN db {"code":"EAI_AGAIN","errno":-3001,"hostname":"db","service":"Practice_App","syscall":"getaddrinfo"}
[31merror[39m: getaddrinfo EAI_AGAIN db {"code":"EAI_AGAIN","errno":-3001,"hostname":"db","service":"Practice_App","syscall":"getaddrinfo"}
